name = "SpInModel"
uuid = "10792a61-568a-4c48-9526-ce895f1a8e73"
authors = ["Giacomo G"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
